name: Publish packages

on:
  push:
    branches:
      - main
      - develop
    paths:
      - ".changeset/**"
  workflow_call:
    secrets:
      BUF_TOKEN:
        required: true
  workflow_dispatch:


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release
    runs-on: [om-com-runner]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@ocean-network-express"
          cache: "npm"

      - name: Config git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          npm install

      - name: Merge mark down file
        run: |
          npm run merge-markdown --workspaces

      - name: Buf login with token
        run: |
          echo ${{secrets.BUF_TOKEN}} | buf registry login --token-stdin
      - name: Buf generate
        run: |
          npm run gen --workspaces

      - name: TypeScript build
        run: |
          npm run tsc-build --workspaces

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run packages-publish
          commit: "ci(changesets): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
