name: CD To DEV Environment

on:
    workflow_dispatch:
        inputs:
            delivery-region:
                type: string
                required: true
                default: asia-southeast1
    push:
        branches:
            - mock-develop
        paths:
            - src/**

jobs:
    cd:
        name: CD
        uses: ./.github/workflows/cd.yml
        with:
            delivery-environment: dev
            delivery-region: ${{ inputs.delivery-region || 'asia-southeast1' }}
            docker-registry: ${{ inputs.delivery-region || 'asia-southeast1' }}-docker.pkg.dev
            artifact-registry: ${{ inputs.delivery-region || 'asia-southeast1' }}-docker.pkg.dev/one-global-chorus-vsm-dev/om-vsm-registry/dev
        secrets:
            SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            CONFIG_REPO_SYNC_DEPLOYMENT_WORKFLOW_PAT: ${{ secrets.CONFIG_REPO_SYNC_DEPLOYMENT_WORKFLOW_PAT }}
