name: CD To TEST Environment

on:
    workflow_dispatch:
        inputs:
            delivery-region:
                type: string
                required: true
                default: asia-southeast1

jobs:
    cd:
        name: CD
        uses: ./.github/workflows/cd.yml
        with:
            delivery-environment: test
            delivery-region: ${{ inputs.delivery-region }}
            docker-registry: ${{ inputs.delivery-region }}-docker.pkg.dev
            artifact-registry: ${{ inputs.delivery-region }}-docker.pkg.dev/one-global-chorus-vsm-test/om-vsm-registry/test
        secrets:
            SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            CONFIG_REPO_SYNC_DEPLOYMENT_WORKFLOW_PAT: ${{ secrets.CONFIG_REPO_SYNC_DEPLOYMENT_WORKFLOW_PAT }}
